# Generated by Django 4.2.20 on 2025-04-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Пост будет виден согласно настройкам видимости и даты публикации.', verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text="Дата и время, когда пост станет доступен (если отмечено 'Опубликовано'). Если пусто, используется текущее время.", null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='Уникальный фрагмент URL. Генерируется автоматически.', max_length=220, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'Всем'), ('followers', 'Только подписчикам'), ('private', 'Только мне')], db_index=True, default='public', help_text='Кто сможет видеть пост после публикации.', max_length=10, verbose_name='Видимость'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['slug'], name='posts_post_slug_59b922_idx'),
        ),
    ]
