# Generated by Django 4.2.20 on 2025-04-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_is_published_alter_post_published_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='Уникальный фрагмент URL. Генерируется автоматически.', max_length=220, null=True, unique=True, verbose_name='Слаг'),
        ),
    ]
