# Generated by Django 4.2.20 on 2025-04-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='Уникальный фрагмент URL. Генерируется автоматически.', max_length=220, unique=True, verbose_name='Слаг'),
        ),
    ]
